# Generated by Django 3.0.6 on 2020-05-25 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenDetails',
            fields=[
                ('service_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateTimeField()),
                ('sex', models.DateTimeField()),
                ('part2order', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ChildrenDetails',
                'verbose_name_plural': 'ChildrenDetails',
                'db_table': 'ChildrenDetails',
                'ordering': ['service_username'],
            },
        ),
        migrations.CreateModel(
            name='InstructionalCourses',
            fields=[
                ('service_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('course_results', models.CharField(max_length=200)),
                ('course_type', models.CharField(max_length=200)),
                ('course_place', models.CharField(max_length=200)),
                ('part2order', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'InstructionalCourses',
                'verbose_name_plural': 'InstructionalCourses',
                'db_table': 'InstructionalCourses',
                'ordering': ['service_username'],
            },
        ),
        migrations.CreateModel(
            name='Kinship',
            fields=[
                ('service_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=200)),
                ('tribe', models.CharField(max_length=200)),
                ('chief', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Kinship',
                'verbose_name_plural': 'Kinship',
                'db_table': 'Kinship',
                'ordering': ['service_username'],
            },
        ),
        migrations.CreateModel(
            name='LeaveDetails',
            fields=[
                ('service_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('leave_type', models.CharField(max_length=200)),
                ('warrant_cash', models.CharField(max_length=200)),
                ('family_warrant', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'LeaveDetails',
                'verbose_name_plural': 'LeaveDetails',
                'db_table': 'LeaveDetails',
                'ordering': ['service_username'],
            },
        ),
        migrations.CreateModel(
            name='PayGroup',
            fields=[
                ('service_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pay_group', models.CharField(max_length=200)),
                ('part2order', models.CharField(max_length=200)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PayGroup',
                'verbose_name_plural': 'PayGroup',
                'db_table': 'PayGroups',
                'ordering': ['service_username'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('service_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('unit', models.CharField(max_length=200)),
                ('sub_unit', models.CharField(max_length=200)),
                ('Religion', models.CharField(max_length=200)),
                ('Date_of_birth', models.CharField(max_length=200)),
                ('lsgcCount', models.CharField(max_length=200)),
                ('Pension', models.CharField(max_length=200)),
                ('civilian_id_no', models.CharField(max_length=200)),
                ('service_id_no', models.CharField(max_length=200)),
                ('kra_no', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Service Members',
                'db_table': 'Profile',
                'ordering': ['service_username'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('service_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rank', models.CharField(max_length=200)),
                ('part2order', models.CharField(max_length=200)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'Promotions',
                'ordering': ['service_username'],
            },
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('service_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Group', models.CharField(max_length=200)),
                ('Class', models.CharField(max_length=200)),
                ('part2order', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'db_table': 'Qualifications',
                'ordering': ['service_username'],
            },
        ),
        migrations.CreateModel(
            name='RegimentaEntries',
            fields=[
                ('service_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_trial', models.DateTimeField()),
                ('place_of_trial', models.CharField(max_length=200)),
                ('trial_co_or_cm', models.CharField(max_length=200)),
                ('part2order', models.CharField(max_length=200)),
                ('non_reconable_service', models.CharField(max_length=200)),
                ('offence', models.TextField(max_length=200)),
                ('award', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'RegimentaEntries',
                'verbose_name_plural': 'RegimentaEntries',
                'db_table': 'RegimentaEntries',
                'ordering': ['service_username'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecords',
            fields=[
                ('service_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('country', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('part2order', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ServiceRecords',
                'verbose_name_plural': 'ServiceRecords',
                'db_table': 'ServiceRecords',
                'ordering': ['service_username'],
            },
        ),
        migrations.CreateModel(
            name='TribalParticulars',
            fields=[
                ('service_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('chief', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('sub_location', models.CharField(max_length=200)),
                ('headman', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Particular',
                'verbose_name_plural': 'Particulars',
                'db_table': 'TribalParticulars',
                'ordering': ['service_username'],
            },
        ),
        migrations.CreateModel(
            name='WifeDetails',
            fields=[
                ('service_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('wife_name', models.CharField(max_length=200)),
                ('date_of_marriage', models.CharField(max_length=200)),
                ('place_of_marriage', models.CharField(max_length=200)),
                ('part2order', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'WifeDetails',
                'verbose_name_plural': 'WifeDetails',
                'db_table': 'WifeDetails',
                'ordering': ['service_username'],
            },
        ),
    ]
