# Generated by Django 3.0.6 on 2020-05-25 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('qrcardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('service_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('terms_of_service', models.CharField(max_length=200)),
                ('date_of_engagement', models.DateTimeField()),
                ('run_out_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'EmploymentDetails',
                'verbose_name_plural': 'EmploymentDetails',
                'db_table': 'EmploymentDetails',
                'ordering': ['service_number'],
            },
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='childrendetails',
            options={'ordering': ['service_number'], 'verbose_name': 'ChildrenDetails', 'verbose_name_plural': 'ChildrenDetails'},
        ),
        migrations.AlterModelOptions(
            name='instructionalcourses',
            options={'ordering': ['service_number'], 'verbose_name': 'InstructionalCourses', 'verbose_name_plural': 'InstructionalCourses'},
        ),
        migrations.AlterModelOptions(
            name='kinship',
            options={'ordering': ['service_number'], 'verbose_name': 'Kinship', 'verbose_name_plural': 'Kinship'},
        ),
        migrations.AlterModelOptions(
            name='leavedetails',
            options={'ordering': ['service_number'], 'verbose_name': 'LeaveDetails', 'verbose_name_plural': 'LeaveDetails'},
        ),
        migrations.AlterModelOptions(
            name='paygroup',
            options={'ordering': ['service_number'], 'verbose_name': 'PayGroup', 'verbose_name_plural': 'PayGroup'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['service_number'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Service Members'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['service_number'], 'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterModelOptions(
            name='qualifications',
            options={'ordering': ['service_number'], 'verbose_name': 'Qualification', 'verbose_name_plural': 'Qualifications'},
        ),
        migrations.AlterModelOptions(
            name='regimentaentries',
            options={'ordering': ['service_number'], 'verbose_name': 'RegimentaEntries', 'verbose_name_plural': 'RegimentaEntries'},
        ),
        migrations.AlterModelOptions(
            name='servicerecords',
            options={'ordering': ['service_number'], 'verbose_name': 'ServiceRecords', 'verbose_name_plural': 'ServiceRecords'},
        ),
        migrations.AlterModelOptions(
            name='tribalparticulars',
            options={'ordering': ['service_number'], 'verbose_name': 'Particular', 'verbose_name_plural': 'Particulars'},
        ),
        migrations.AlterModelOptions(
            name='wifedetails',
            options={'ordering': ['service_number'], 'verbose_name': 'WifeDetails', 'verbose_name_plural': 'WifeDetails'},
        ),
        migrations.RenameField(
            model_name='childrendetails',
            old_name='service_username',
            new_name='service_number',
        ),
        migrations.RenameField(
            model_name='instructionalcourses',
            old_name='service_username',
            new_name='service_number',
        ),
        migrations.RenameField(
            model_name='kinship',
            old_name='service_username',
            new_name='service_number',
        ),
        migrations.RenameField(
            model_name='leavedetails',
            old_name='service_username',
            new_name='service_number',
        ),
        migrations.RenameField(
            model_name='paygroup',
            old_name='service_username',
            new_name='service_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='service_username',
            new_name='service_number',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='service_username',
            new_name='service_number',
        ),
        migrations.RenameField(
            model_name='qualifications',
            old_name='service_username',
            new_name='service_number',
        ),
        migrations.RenameField(
            model_name='regimentaentries',
            old_name='service_username',
            new_name='service_number',
        ),
        migrations.RenameField(
            model_name='servicerecords',
            old_name='service_username',
            new_name='service_number',
        ),
        migrations.RenameField(
            model_name='tribalparticulars',
            old_name='service_username',
            new_name='service_number',
        ),
        migrations.RenameField(
            model_name='wifedetails',
            old_name='service_username',
            new_name='service_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='profile',
            name='ROD',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
