# Generated by Django 3.0.6 on 2020-05-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcardapp', '0003_auto_20200525_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Date_of_birth',
            field=models.DateField(),
        ),
    ]
